### ISSUE TITLE
Incompatible with Komodo Edit/IDE 10

### ISSUE THREAD

**Issue by techdude** [Komodo/Abyss-Skin#10]
This skin is incompatable with KE10.

**Comment by th3coop** [comment]
I don't think there is any plan to upgrade this skin to work with Komodo 10 for 2 reasons:
1. Too much has changed in how color schemes works
2. The default colour scheme is basically Abyss

Have a look at the default skin in Prefs > Color schemes.  If you want to change it and can't figure out how to get the desired changes as in the [Komodo forums](http://forum.komodoide.com/)
