### ISSUE TITLE
grey header if appearance vertical tabs is enabled

### ISSUE THREAD

**Issue by babobski** [Komodo/Abyss-Skin#2]
if you enable vertical tabs on the side panel layout the headers arrent styled.
![snap 2014-11-13 at 18 11 42](https://cloud.githubusercontent.com/assets/3530262/5032794/e23cc49c-6b60-11e4-9fb9-a85ebb523f8e.png)
![snap 2014-11-13 at 18 11 00](https://cloud.githubusercontent.com/assets/3530262/5032856/5adb149e-6b61-11e4-994c-7a486ef73df8.png)
installed spacemodo but got the same bug there

**Comment by Naatan** [comment]
You fixed this in https://github.com/Komodo/Abyss-Skin/pull/5

Closing :)
