### ISSUE TITLE
Places/Open Files and Toolbox panels are not themed (Mac OSX 10.10/Retina)

### ISSUE THREAD

**Issue by thelsel** [Komodo/Abyss-Skin#4]
I have a Mac laptop with a Retina display running Mac OSX 10.10. I've downloaded Komodo Edit 9 and tried to switch to the Abyss theme. The Places/Open Files and Toolbox sidebars do not get themed:

![screen shot 2015-04-25 at 9 40 27 am](https://cloud.githubusercontent.com/assets/11302225/7333112/b95f4bea-eb2f-11e4-873f-8080cf4c0775.png)

I don't see this issue with my desktop, which is running Mac OSX 10.9 on a standard screen, nor have I seen this on my Windows 7 desktop.

**Comment by thelsel** [comment]
Actually. this has nothing to do with a Retina display. I upgraded my iMac, which does not have a Retina display, to OSX 10.10 and am having the same issue.

**Comment by Naatan** [comment]
Should be fixed in the latest nightly. Note you need to reapply Abyss to work around the issue this time.

**Comment by thelsel** [comment]
Thanks Naatan. Looks awesome. I really appreciate your hard work.
