### ISSUE TITLE
issue removing old version

### ISSUE THREAD

**Issue by ghost** [Komodo/Abyss-Skin#7]
I have searched my AppData folder but cannot find any abyss files. I tried to install abyss_skin-1.1.1-ko.xpi from file but nothing happens. I still have a reference to the old version 1.0 abyss skin and I think that might be conflicting? thanks

**Comment by th3coop** [comment]
Could you explain more clearly what is happening?  What is the issue?  When did it start?  

When you say that you have a references to the old, where is this reference?  In the add-ons dialog?  Can you disable or uninstall it if it's still there?

**Comment by ghost** [comment]
i have since upgraded to version 9 which fixed the issue. by references I meant in the addons, where I didn't see any option to uninstall...
anyway, solved by uninstall, delete appdata, reinstall new version... where abyss is not an addon... thanks.

**Comment by th3coop** [comment]
SOunds good.  For future reference, you wiped out all of your Komodo preferences (custom keybindings, color scheme config, etc.) when you deleted your AppData Komodo content.  That wasn't necessary in this use case.   You may be aware of that but if you're not or someone else that reads this is not aware, don't do that unless you are sure you need to.  Even then, you can just remove portions of the profile.

Either way, glad you're now sorted @bobombolo

**Comment by Naatan** [comment]
Abyss was baked into Komodo 9.1, so you wouldnt have been able to remove it from that.
